### ISSUE TITLE
alex configuration not working

### ISSUE THREAD

**Issue by kaiuri** [iamcco/coc-diagnostic#142]
`alex` not working when used with `alexjs`

https://github.com/iamcco/coc-diagnostic/blob/e93bc667d4a5fe715f8bc9c8a80d101032963d4e/src/config.ts#L122-L142

it does after replacing `alexjs` with `alex`.

Can I open a pull request to change it?

**Comment by iamcco** [comment]
PR is welcome

**Comment by Freed-Wu** [comment]
This is because there is another program named alex written in haskell, so the packager of Archlinux rename it to alexjs to avoid conflict (this alex is written in javascript). I agree to this change because I think users can create a symlink by themselves. However, why only change one alexjs not all? alex use different command option for different filetypes: <https://github.com/iamcco/coc-diagnostic/pull/143/files#diff-c3095d5010e65c52737a98a5d618ea24049ebe90c8470752426081d70ed6e012L147> and <https://github.com/iamcco/coc-diagnostic/pull/143/files#diff-c3095d5010e65c52737a98a5d618ea24049ebe90c8470752426081d70ed6e012L169>
